site_name: Jardim do Conhecimento

repo_name: Yggdrasil
repo_url: 'https://github.com/OrcestraGamificacao/Yggdrasil-Docs'

docs_dir: yggdrasil_docs/
site_dir: docs/

copyright: 'Copyright &copy; 2020 Yggdrasil'

theme:
  name: 'material'
  favicon: Images/Logo.svg
  logo: Images/Logo.svg
  features:
    - navigation.tabs
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Início: index.md
  - Doc Arquitetura:
    - architecture.md
  - Doc Visão:
    - vision.md
  - Backlog:
    - backlog.md
  - Políticas:
    - Branch: Policies/branch.md
    - Commit: Policies/commit.md
    - Issue: Policies/issue.md
    - PR: Policies/pr.md